version: '3.4'

services:
  yandexmarketservice.api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ya-image
    ports:
      - 5000:80
    restart: always
    container_name: ya-market
    mem_limit: 500m
    mem_reservation: 30m
